window.HSK_DATA = {
  brand: {
    appName: "HSK Mastery",
    legalName: "TODO: company legal name",
    logoStatus: "TODO: design original logo. Do not copy SuperTest/HSKOnline marks.",
    supportEmail: "TODO: support email",
    address: "TODO: company address",
  },
  locales: [
    ["vi", "Tiếng Việt"],
    ["en", "English"],
    ["zh", "简体中文"],
    ["ja", "日本語"],
    ["ko", "한국어"],
    ["th", "ภาษาไทย"],
    ["ru", "Русский"],
    ["es", "español"],
    ["fr", "Français"],
    ["id", "Bahasa Indonesia"],
    ["de", "German"],
    ["pt", "Português"],
    ["it", "Italian"],
  ],
  sourceLocale: "vi",
  fallbackLocale: "en",
  translationPolicy: {
    sourceLanguage: "Tiếng Việt là ngôn ngữ gốc cho giao diện và nội dung sản phẩm.",
    fallbackLanguage: "Các ngôn ngữ khác chỉ bật sau khi có bản dịch được rà soát.",
    machineTranslation: "Dịch máy/AI chỉ dùng để tạo bản nháp; nội dung học công bố cần người hoặc giáo viên rà soát.",
    learningContent: "Đề bài, đáp án và transcript tiếng Trung là dữ liệu học gốc; giải thích và giao diện sẽ được bản địa hóa theo từng ngôn ngữ.",
  },
  dict: {
    vi: {
      appTitle: "HSK Mastery - luyện thi HSK thông minh",
      appSubtitle: "Luyện tập, thi thử, sửa bài viết, ôn câu sai và cá nhân hóa lộ trình.",
      overview: "Tổng quan",
      practice: "Luyện tập",
      mock: "Thi thử",
      writing: "Viết",
      vocab: "Từ vựng",
      repository: "Kho cá nhân",
      pricing: "Gói học",
      system: "Hệ thống",
      profile: "Hồ sơ",
      content: "Nội dung",
      language: "Ngôn ngữ",
      target: "Mục tiêu",
      readiness: "Sẵn sàng",
      accuracy: "Độ đúng",
      dueReviews: "Cần ôn",
      start: "Bắt đầu",
      submit: "Nộp bài",
      save: "Lưu",
      answer: "Trả lời",
      analysis: "Phân tích",
      correct: "Đáp án đúng",
      wrong: "Cần ôn lại",
      learnOnline: "Học online",
      aboutTest: "Giới thiệu kỳ thi",
      testPlan: "Lịch thi",
      testRegulation: "Quy định thi",
      downloadApp: "Tải ứng dụng",
      corporateServices: "Dịch vụ doanh nghiệp",
      upgrade: "Nâng cấp",
      contentAdmin: "Quản trị nội dung",
      login: "Đăng nhập",
      auth: "Tài khoản",
      account: "Tài khoản",
      accountCenter: "Trung tâm tài khoản",
      tutoring: "Gia sư",
      corporate: "Doanh nghiệp",
      mockTests: "Thi thử",
      vocabulary: "Từ vựng",
      hskLevels: "HSK cấp 1-9",
      writingCorrection: "Sửa bài viết",
      oneOnOneTutoring: "Gia sư 1-1",
      myExercise: "Bài luyện của tôi",
      aboutHsk: "Về HSK",
      platform: "Nền tảng",
      admin: "Quản trị",
      superAdmin: "Super Admin",
      listening: "Nghe",
      reading: "Đọc",
      tests: "Đề thi thử",
      ourSpecialties: "Điểm nổi bật",
      learnerChoice: "Lựa chọn của người học",
      translationAdmin: "Quản trị bản dịch",
      sourceLanguage: "Ngôn ngữ gốc",
      fallbackLanguage: "Ngôn ngữ dự phòng",
      coverage: "Độ phủ",
      missingKeys: "Key còn thiếu",
      section: "Phần",
      progress: "Tiến độ",
      correctAnswerNumber: "Số đúng / số đã trả lời",
      singleTraining: "Luyện riêng",
      smartQuiz: "Luyện thông minh",
      open: "Mở",
      vipLocked: "Khóa VIP",
      overallProgress: "Tiến độ chung",
      totalAnswer: "Tổng câu trả lời",
      right: "Đúng",
      time: "Thời gian",
      answerSheet: "Phiếu trả lời",
      mockCatalog: "Danh sách đề thi thử",
      mockExamConsole: "Phòng thi thử",
      testContent: "Nội dung thi",
      appFeatureModel: "Mô hình tính năng ứng dụng",
      bookTrial: "Đặt lịch học thử",
      saveItem: "Lưu câu",
      addNote: "Thêm ghi chú",
      next: "Tiếp",
      previous: "Trước",
      pauseTimer: "Tạm dừng",
      startSelectedMock: "Bắt đầu đề đã chọn",
      translation: "Dịch",
      speaking: "Nói",
      advancedHsk: "HSK 7-9 nâng cao",
      advancedExam: "Bài thi HSK 7-9",
      productivePractice: "Luyện kỹ năng tạo sinh",
      recordSpeaking: "Ghi âm bài nói",
      stopRecording: "Dừng ghi âm",
      recordingReady: "Bản ghi đã sẵn sàng",
      recordingError: "Không mở được micro",
      localRecording: "Ghi âm cục bộ",
      rubricFeedback: "Nhận xét theo rubric",
      saveDraft: "Lưu bản nháp",
      aiFeedback: "Nhận xét AI",
    },
    en: {
      appTitle: "HSK Mastery - intelligent HSK preparation",
      appSubtitle: "Practice, mock tests, writing feedback, mistake review, and personalized plans.",
      overview: "Overview",
      practice: "Practice",
      mock: "Mock test",
      writing: "Writing",
      vocab: "Vocabulary",
      repository: "Repository",
      pricing: "Pricing",
      system: "System",
      profile: "Profile",
      content: "Content",
      language: "Language",
      target: "Target",
      readiness: "Readiness",
      accuracy: "Accuracy",
      dueReviews: "Due reviews",
      start: "Start",
      submit: "Submit",
      save: "Save",
      answer: "Answer",
      analysis: "Analysis",
      correct: "Correct",
      wrong: "Review again",
      learnOnline: "Learn Online",
      aboutTest: "About Test",
      testPlan: "Test Plan",
      testRegulation: "Test Regulation",
      downloadApp: "Download App",
      corporateServices: "Corporate Services",
      upgrade: "Upgrade",
      contentAdmin: "Content Admin",
      login: "Login",
      auth: "Auth",
      account: "Account",
      accountCenter: "Account center",
      tutoring: "Tutoring",
      corporate: "Corporate",
      mockTests: "Mock Tests",
      vocabulary: "Vocabulary",
      hskLevels: "HSK Level 1-9",
      writingCorrection: "Writing correction",
      oneOnOneTutoring: "One-on-one tutoring",
      myExercise: "My exercise",
      aboutHsk: "About HSK",
      platform: "Platform",
      admin: "Admin",
      superAdmin: "Super Admin",
      listening: "Listening",
      reading: "Reading",
      tests: "Mock tests",
      ourSpecialties: "Our Specialties",
      learnerChoice: "The choice of learners",
      translationAdmin: "Translation admin",
      sourceLanguage: "Source language",
      fallbackLanguage: "Fallback language",
      coverage: "Coverage",
      missingKeys: "Missing keys",
      section: "Section",
      progress: "Progress",
      correctAnswerNumber: "Correct number/answer number",
      singleTraining: "Single Training",
      smartQuiz: "Smart Quiz",
      open: "Open",
      vipLocked: "VIP locked",
      overallProgress: "Overall progress",
      totalAnswer: "Total Answer",
      right: "Right",
      time: "Time",
      answerSheet: "Answer sheet",
      mockCatalog: "Mock catalog",
      mockExamConsole: "Mock exam console",
      testContent: "Test Content",
      appFeatureModel: "App feature model",
      bookTrial: "Book trial",
      saveItem: "Save item",
      addNote: "Add note",
      next: "Next",
      previous: "Previous",
      pauseTimer: "Pause timer",
      startSelectedMock: "Start selected mock",
      translation: "Translation",
      speaking: "Speaking",
      advancedHsk: "Advanced HSK 7-9",
      advancedExam: "HSK 7-9 exam",
      productivePractice: "Productive skill practice",
      recordSpeaking: "Record speaking",
      stopRecording: "Stop recording",
      recordingReady: "Recording ready",
      recordingError: "Microphone unavailable",
      localRecording: "Local recording",
      rubricFeedback: "Rubric feedback",
      saveDraft: "Save draft",
      aiFeedback: "AI feedback",
    },
  },
  skills: [
    { key: "listening", label: "Listening", vi: "Nghe" },
    { key: "reading", label: "Reading", vi: "Đọc" },
    { key: "writing", label: "Writing", vi: "Viết" },
    { key: "translation", label: "Translation", vi: "Dịch" },
    { key: "speaking", label: "Speaking", vi: "Nói" },
    { key: "tests", label: "Mock tests", vi: "Thi thử" },
  ],
  levels: [
    {
      id: 1,
      name: "HSK 1",
      words: 150,
      readiness: 32,
      sections: {
        listening: ["Đúng hoặc sai", "Nối câu với tranh", "Nối hội thoại với tranh", "Chọn đáp án đúng"],
        reading: ["Đúng hoặc sai", "Chọn tranh đúng", "Chọn câu đúng", "Điền vào chỗ trống"],
        writing: [],
        tests: ["Đề thi thử số 1", "Đề thi thử số 2", "Gói đề đã kiểm chứng"],
      },
    },
    {
      id: 2,
      name: "HSK 2",
      words: 300,
      readiness: 21,
      sections: {
        listening: ["Đúng hoặc sai", "Nối hội thoại với tranh", "Câu hỏi hội thoại", "Câu hỏi hội thoại"],
        reading: ["Chọn tranh đúng", "Điền vào chỗ trống", "Đúng hoặc sai", "Chọn câu đúng"],
        writing: [],
        tests: ["Đề thi thử số 1", "Đề thi thử số 2", "Gói đề đã kiểm chứng"],
      },
    },
    {
      id: 3,
      name: "HSK 3",
      words: 600,
      readiness: 14,
      sections: {
        listening: ["Chọn tranh đúng", "Đúng hoặc sai", "Câu hỏi hội thoại", "Câu hỏi hội thoại"],
        reading: ["Chọn câu đúng", "Điền vào chỗ trống", "Đọc hiểu"],
        writing: ["Sắp xếp câu", "Viết chữ Hán"],
        tests: ["Đề thi thử số 1", "Gói đề đã kiểm chứng", "Đề mini thích ứng"],
      },
    },
    {
      id: 4,
      name: "HSK 4",
      words: 1200,
      readiness: 9,
      sections: {
        listening: ["Đúng hoặc sai", "Câu hỏi hội thoại", "Câu hỏi hội thoại"],
        reading: ["Điền vào chỗ trống", "Sắp xếp câu", "Chọn đáp án đúng"],
        writing: ["Sắp xếp câu", "Viết câu theo tranh"],
        tests: ["Đề thi thử số 1", "Gói đề đã kiểm chứng", "Đề mini thích ứng"],
      },
    },
    {
      id: 5,
      name: "HSK 5",
      words: 2500,
      readiness: 6,
      sections: {
        listening: ["Câu hỏi hội thoại", "Câu hỏi đoạn nghe"],
        reading: ["Điền vào chỗ trống", "Chọn câu đúng", "Đọc hiểu"],
        writing: ["Sắp xếp câu", "Viết đoạn theo từ khóa", "Viết bài theo tranh"],
        tests: ["Đề thi thử số 1", "Gói đề đã kiểm chứng", "Đề mini thích ứng"],
      },
    },
    {
      id: 6,
      name: "HSK 6",
      words: 5000,
      readiness: 4,
      sections: {
        listening: ["Chọn câu phù hợp", "Câu hỏi phỏng vấn", "Câu hỏi đoạn nghe"],
        reading: ["Tìm câu sai", "Điền vào chỗ trống", "Điền vào chỗ trống", "Đọc hiểu"],
        writing: ["Viết tóm tắt bài đọc"],
        tests: ["Đề thi thử số 1", "Gói đề đã kiểm chứng", "Đề mini thích ứng"],
      },
    },
    {
      id: 7,
      name: "HSK 7",
      band: "advanced",
      words: 11092,
      readiness: 3,
      sections: {
        listening: ["Tin tức và phỏng vấn", "Bài giảng học thuật", "Thảo luận nhiều lượt"],
        reading: ["Đọc học thuật", "Đọc văn hóa - xã hội", "Suy luận quan điểm tác giả"],
        writing: ["Tóm tắt nguồn đọc/nghe", "Bài nghị luận 350-500 chữ"],
        translation: ["Dịch Trung - Việt", "Dịch Việt - Trung", "Dịch thông tin ứng dụng"],
        speaking: ["Trả lời chủ đề", "Tóm tắt lại nội dung nghe", "Trình bày quan điểm"],
        tests: ["Đề Advanced HSK 7-9", "Đề mini kỹ năng yếu", "Kho đề nâng cao"],
      },
    },
    {
      id: 8,
      name: "HSK 8",
      band: "advanced",
      words: 11092,
      readiness: 2,
      sections: {
        listening: ["Bài giảng chuyên sâu", "Phỏng vấn tốc độ tự nhiên", "Tranh luận học thuật"],
        reading: ["Bài đọc dài", "So sánh lập luận", "Đọc văn bản chuyên ngành"],
        writing: ["Bình luận quan điểm", "Viết báo cáo ngắn", "Tái cấu trúc văn bản"],
        translation: ["Dịch đoạn văn nghị luận", "Dịch văn bản thực dụng", "Dịch hai chiều có thuật ngữ"],
        speaking: ["Thuyết trình ngắn", "Phản biện quan điểm", "Tóm tắt và đánh giá"],
        tests: ["Đề Advanced HSK 7-9", "Đề mô phỏng 210 phút", "Kho đề nâng cao"],
      },
    },
    {
      id: 9,
      name: "HSK 9",
      band: "advanced",
      words: 11092,
      readiness: 1,
      sections: {
        listening: ["Diễn thuyết học thuật", "Tin chuyên sâu", "Đối thoại đa quan điểm"],
        reading: ["Văn bản học thuật dài", "Văn học - văn hóa", "Đánh giá lập luận trừu tượng"],
        writing: ["Bài luận học thuật", "Tổng hợp nhiều nguồn", "Viết lập luận nâng cao"],
        translation: ["Dịch học thuật", "Dịch văn hóa - xã hội", "Dịch chính xác sắc thái"],
        speaking: ["Thuyết trình học thuật", "Phản biện có cấu trúc", "Trình bày giải pháp"],
        tests: ["Đề Advanced HSK 7-9", "Đề mô phỏng 210 phút", "Kho đề nâng cao"],
      },
    },
  ],
  advancedExam: {
    name: "HSK 7-9 Advanced",
    levels: [7, 8, 9],
    questions: 98,
    duration: 210,
    mode: "Internet-based",
    resultModel: "Một bài thi chung phân loại kết quả dưới HSK7, HSK7, HSK8 hoặc HSK9.",
    skills: ["Nghe", "Đọc", "Viết", "Dịch", "Nói"],
    contentBoundary: "Số câu và thời lượng tổng bám thông tin công khai. Câu hỏi, audio, đoạn đọc, đề dịch và đề nói phải là nội dung tự biên soạn hoặc được cấp phép.",
  },
  practiceQuestions: [
    {
      id: "hsk1-l-tf-001",
      level: 1,
      skill: "listening",
      section: "Đúng hoặc sai",
      type: "Đúng hoặc sai",
      difficulty: 1,
      source: "original",
      assetStatus: "needs-recorded-audio",
      prompt: "Lời thoại: 你好，我叫安娜。 Mệnh đề: 她叫安娜。",
      options: ["Đúng", "Sai"],
      answer: "Đúng",
      transcript: "你好，我叫安娜。",
      translation: "Xin chào, tôi tên là Anna.",
      analysis: "Câu nghe nói rõ người nói tên là Anna, nên mệnh đề 'cô ấy tên Anna' là đúng.",
      grammar: "叫 + name: dùng để nói tên.",
    },
    {
      id: "hsk1-l-mp-002",
      level: 1,
      skill: "listening",
      section: "Chọn đáp án đúng",
      type: "Chọn đáp án đúng",
      difficulty: 1,
      source: "original",
      assetStatus: "needs-recorded-audio",
      prompt: "Lời thoại: 今天很冷。 Câu hỏi: 今天天气怎么样？",
      options: ["很热", "很冷", "很好吃", "很忙"],
      answer: "很冷",
      transcript: "今天很冷。",
      translation: "Hôm nay rất lạnh.",
      analysis: "Từ khóa là 冷, nghĩa là lạnh. Các lựa chọn khác là nóng, ngon, bận.",
      grammar: "很 + adjective.",
    },
    {
      id: "hsk1-r-tf-001",
      level: 1,
      skill: "reading",
      section: "Đúng hoặc sai",
      type: "Đúng hoặc sai",
      difficulty: 1,
      source: "original",
      prompt: "Đoạn đọc: 我是学生。 Mệnh đề: 他是老师。",
      options: ["Đúng", "Sai"],
      answer: "Sai",
      translation: "Tôi là học sinh. Mệnh đề: Anh ấy là giáo viên.",
      analysis: "Text nói 学生, không phải 老师. Mệnh đề đổi chủ thể và nghề nghiệp nên sai.",
      grammar: "是 dùng để nối chủ ngữ với danh từ định danh.",
    },
    {
      id: "hsk1-r-gap-002",
      level: 1,
      skill: "reading",
      section: "Điền vào chỗ trống",
      type: "Điền vào chỗ trống",
      difficulty: 1,
      source: "original",
      prompt: "我每天___水。",
      options: ["喝", "去", "看", "买"],
      answer: "喝",
      translation: "Tôi uống nước mỗi ngày.",
      analysis: "水 là nước; động từ phù hợp là 喝. 去 là đi, 看 là xem, 买 là mua.",
      grammar: "Subject + time + verb + object.",
    },
    {
      id: "hsk2-l-dialog-001",
      level: 2,
      skill: "listening",
      section: "Câu hỏi hội thoại",
      type: "Chọn đáp án đúng",
      difficulty: 2,
      source: "original",
      assetStatus: "needs-recorded-audio",
      prompt: "Hội thoại: 男：你什么时候去学校？女：我八点去。 Câu hỏi: 女的几点去学校？",
      options: ["七点", "八点", "九点", "十点"],
      answer: "八点",
      transcript: "你什么时候去学校？我八点去。",
      translation: "Bạn đi trường lúc mấy giờ? Tôi đi lúc 8 giờ.",
      analysis: "Câu trả lời trực tiếp là 八点.",
      grammar: "什么时候 hỏi thời gian; 点 dùng cho giờ.",
    },
    {
      id: "hsk2-r-gap-001",
      level: 2,
      skill: "reading",
      section: "Điền vào chỗ trống",
      type: "Điền vào chỗ trống",
      difficulty: 2,
      source: "original",
      prompt: "这个苹果比那个苹果___。",
      options: ["大", "在", "从", "得"],
      answer: "大",
      translation: "Quả táo này lớn hơn quả táo kia.",
      analysis: "Cấu trúc 比 dùng để so sánh, sau 比 cần tính từ 大.",
      grammar: "A 比 B + adjective.",
    },
    {
      id: "hsk3-r-order-001",
      level: 3,
      skill: "reading",
      section: "Chọn câu đúng",
      type: "Sắp xếp câu",
      difficulty: 3,
      source: "original",
      prompt: "Sắp xếp các mảnh câu thành một câu tự nhiên.",
      options: ["我", "已经", "做完", "作业了"],
      answer: "我已经做完作业了",
      translation: "Tôi đã làm xong bài tập rồi.",
      analysis: "已经 đặt trước động từ để nhấn mạnh hành động đã hoàn thành; 了 đánh dấu hoàn tất.",
      grammar: "已经 + verb phrase + 了.",
    },
    {
      id: "hsk3-w-char-001",
      level: 3,
      skill: "writing",
      section: "Viết chữ Hán",
      type: "Viết ngắn",
      difficulty: 3,
      source: "original",
      prompt: "Dùng 以前 để viết một câu về thói quen học tập của bạn.",
      options: ["Nộp trong không gian luyện viết"],
      answer: "我以前每天晚上学习汉语。",
      translation: "Trước đây tôi học tiếng Trung mỗi tối.",
      analysis: "Câu mẫu dùng 以前 để chỉ thói quen trong quá khứ.",
      grammar: "Time phrase + subject + action.",
    },
    {
      id: "hsk4-r-order-001",
      level: 4,
      skill: "reading",
      section: "Sắp xếp câu",
      type: "Sắp xếp câu",
      difficulty: 4,
      source: "original",
      prompt: "Sắp xếp các cụm thành một câu tự nhiên.",
      options: ["因为下雨", "所以我们", "取消了", "今天的比赛"],
      answer: "因为下雨，所以我们取消了今天的比赛",
      translation: "Vì trời mưa nên chúng tôi đã hủy trận đấu hôm nay.",
      analysis: "因为 nêu nguyên nhân, 所以 dẫn kết quả. 宾语 今天的比赛 đứng sau 取消了.",
      grammar: "因为..., 所以...",
    },
    {
      id: "hsk4-w-picture-001",
      level: 4,
      skill: "writing",
      section: "Viết câu theo tranh",
      type: "Viết ngắn",
      difficulty: 4,
      source: "original",
      assetStatus: "needs-original-image",
      prompt: "Mô tả tranh: một người đang tập thể dục trong công viên. Viết một câu với 一边...一边...",
      options: ["Nộp trong không gian luyện viết"],
      answer: "他一边听音乐一边在公园跑步。",
      translation: "Anh ấy vừa nghe nhạc vừa chạy bộ trong công viên.",
      analysis: "Một câu tốt dùng đúng cấu trúc song song 一边...一边... và bối cảnh công viên.",
      grammar: "一边 + action 1 + 一边 + action 2.",
    },
    {
      id: "hsk5-r-comp-001",
      level: 5,
      skill: "reading",
      section: "Reading comprehension",
      type: "Chọn đáp án đúng",
      difficulty: 5,
      source: "original",
      prompt: "Đoạn đọc: 提高效率不等于工作更长时间，而是要学会安排任务的先后顺序。 Câu hỏi: 这句话主要说明什么？",
      options: ["应该少休息", "应该延长工作时间", "应该合理安排任务", "应该同时做所有事情"],
      answer: "应该合理安排任务",
      translation: "Nâng cao hiệu suất không có nghĩa là làm lâu hơn, mà là biết sắp xếp thứ tự ưu tiên.",
      analysis: "Ý chính là 合理安排任务, không phải kéo dài thời gian hay làm mọi việc cùng lúc.",
      grammar: "不等于...而是... dùng để đối lập và làm rõ định nghĩa.",
    },
    {
      id: "hsk5-w-keyword-001",
      level: 5,
      skill: "writing",
      section: "Viết đoạn theo từ khóa",
      type: "Bài viết",
      difficulty: 5,
      source: "original",
      prompt: "Viết đoạn khoảng 80 chữ, dùng các từ: 经验, 机会, 提高.",
      options: ["Nộp trong không gian luyện viết"],
      answer: "每一次练习都是提高能力的机会。只要认真总结经验，学习效率就会越来越高。",
      translation: "Mỗi lần luyện tập là một cơ hội nâng cao năng lực...",
      analysis: "Bài tốt cần dùng đủ từ khóa, mạch lạc và có quan điểm rõ.",
      grammar: "只要..., 就... điều kiện - kết quả.",
    },
    {
      id: "hsk6-l-interview-001",
      level: 6,
      skill: "listening",
      section: "Câu hỏi phỏng vấn",
      type: "Chọn đáp án đúng",
      difficulty: 6,
      source: "original",
      assetStatus: "needs-recorded-audio",
      prompt: "Tóm tắt lời phỏng vấn: người nói cho rằng học online tiện lợi, nhưng nếu thiếu tự giác thì hiệu quả hạn chế. Câu hỏi: thái độ của người nói là gì?",
      options: ["Hoàn toàn tiêu cực", "Cân bằng và thận trọng", "Không liên quan", "Chỉ hào hứng"],
      answer: "Cân bằng và thận trọng",
      transcript: "网络学习很方便，不过如果没有自律，效果也会很有限。",
      translation: "Học online rất tiện, nhưng nếu không tự giác thì hiệu quả cũng hạn chế.",
      analysis: "Người nói công nhận ưu điểm nhưng nhấn mạnh điều kiện tự giác, nên thái độ cân bằng và thận trọng.",
      grammar: "不过 introduces contrast.",
    },
    {
      id: "hsk6-r-error-001",
      level: 6,
      skill: "reading",
      section: "Tìm câu sai",
      type: "Tìm câu sai",
      difficulty: 6,
      source: "original",
      prompt: "Chọn câu có vấn đề ngữ pháp.",
      options: [
        "他把这个问题解释得很清楚。",
        "这本书对我影响很大。",
        "由于天气不好，所以活动被推迟了。",
        "我非常同意你的看法很有道理。",
      ],
      answer: "我非常同意你的看法很有道理。",
      translation: "Câu sai ghép chồng hai vị ngữ không tự nhiên.",
      analysis: "Nên sửa thành 我非常同意你的看法 hoặc 我觉得你的看法很有道理.",
      grammar: "Tránh ghép hai cấu trúc nhận định trùng nhau.",
    },
    {
      id: "hsk6-w-summary-001",
      level: 6,
      skill: "writing",
      section: "Viết tóm tắt bài đọc",
      type: "Bài viết",
      difficulty: 6,
      source: "original",
      prompt: "Đọc một bài khoảng 900 chữ, ẩn bài gốc, sau đó viết bản tóm tắt ngắn gọn. Nguồn bài đọc phải là nội dung tự biên soạn hoặc được cấp phép.",
      options: ["Nộp trong không gian luyện viết"],
      answer: "Bài tóm tắt đạt điểm cao cần giữ sự kiện chính, logic và giọng trung lập.",
      translation: "Bài tóm tắt cần giữ ý chính, logic và giọng trung lập.",
      analysis: "HSK6 writing should grade completeness, accuracy, structure, vocabulary and character control.",
      grammar: "Summarization rubric, not one fixed answer.",
    },
    {
      id: "hsk7-l-news-001",
      level: 7,
      skill: "listening",
      section: "Tin tức và phỏng vấn",
      type: "Chọn đáp án đúng",
      difficulty: 7,
      source: "original",
      assetStatus: "needs-recorded-audio",
      prompt: "Lời thoại: 这项研究并不是要否定传统课堂，而是提醒学校把线上资源和面对面讨论结合起来。 Câu hỏi: Người nói nhấn mạnh điều gì?",
      options: ["Loại bỏ lớp học truyền thống", "Kết hợp tài nguyên online với thảo luận trực tiếp", "Chỉ học một mình", "Giảm vai trò của giáo viên"],
      answer: "Kết hợp tài nguyên online với thảo luận trực tiếp",
      transcript: "这项研究并不是要否定传统课堂，而是提醒学校把线上资源和面对面讨论结合起来。",
      translation: "Nghiên cứu này không phủ nhận lớp học truyền thống, mà nhắc nhà trường kết hợp tài nguyên trực tuyến với thảo luận trực tiếp.",
      analysis: "Cấu trúc 并不是...而是... phủ định cách hiểu sai và nêu trọng tâm thật.",
      grammar: "并不是 A，而是 B: không phải A, mà là B.",
    },
    {
      id: "hsk7-r-social-001",
      level: 7,
      skill: "reading",
      section: "Đọc văn hóa - xã hội",
      type: "Suy luận quan điểm",
      difficulty: 7,
      source: "original",
      prompt: "Đoạn đọc: 城市更新如果只追求商业效率，可能会削弱社区原有的互助关系。因此，规划者需要在经济活力和居民归属感之间寻找平衡。 Câu hỏi: Tác giả có thái độ nào?",
      options: ["Ủng hộ thương mại hóa bằng mọi giá", "Phản đối mọi thay đổi đô thị", "Nhấn mạnh cân bằng giữa phát triển và cộng đồng", "Chỉ quan tâm đến kiến trúc"],
      answer: "Nhấn mạnh cân bằng giữa phát triển và cộng đồng",
      translation: "Đổi mới đô thị nếu chỉ chạy theo hiệu quả thương mại có thể làm yếu quan hệ hỗ trợ trong cộng đồng.",
      analysis: "Từ khóa là 平衡. Tác giả không phản đối phát triển, mà yêu cầu cân bằng với cảm giác thuộc về của cư dân.",
      grammar: "如果...可能会...因此... biểu thị điều kiện, hệ quả và kết luận.",
    },
    {
      id: "hsk7-w-summary-001",
      level: 7,
      skill: "writing",
      section: "Tóm tắt nguồn đọc/nghe",
      type: "Viết tóm tắt",
      difficulty: 7,
      source: "original",
      prompt: "Đọc/nghe một đoạn 600-800 chữ về học trực tuyến, sau đó viết bản tóm tắt 250-300 chữ, giữ ba ý chính và giọng trung lập. Nội dung nguồn cần tự biên soạn hoặc cấp phép.",
      options: ["Nộp trong không gian luyện viết"],
      answer: "Bài đạt yêu cầu phải giữ luận điểm chính, quan hệ nguyên nhân - kết quả và không thêm ý riêng.",
      translation: "Nhiệm vụ viết nâng cao dạng tóm tắt nhiều nguồn.",
      analysis: "Rubric chấm theo độ đầy đủ, tính chính xác, mạch logic, từ vựng học thuật và kiểm soát chữ Hán.",
      grammar: "Tập trung vào cấu trúc tóm tắt: 背景 - 核心观点 - 影响 - 结论.",
      rubric: ["Độ đầy đủ ý", "Tính chính xác", "Mạch lạc", "Từ vựng học thuật", "Kiểm soát chữ Hán"],
    },
    {
      id: "hsk7-tr-vizhong-001",
      level: 7,
      skill: "translation",
      section: "Dịch Việt - Trung",
      type: "Dịch đoạn văn",
      difficulty: 7,
      source: "original",
      prompt: "Dịch sang tiếng Trung: Việc học ngoại ngữ hiệu quả không chỉ phụ thuộc vào thời gian, mà còn phụ thuộc vào cách người học phản hồi với lỗi sai của mình.",
      options: ["Nộp bản dịch"],
      answer: "有效的外语学习不仅取决于时间，还取决于学习者如何回应自己的错误。",
      translation: "Effective language learning depends not only on time, but also on how learners respond to their own mistakes.",
      analysis: "Bản dịch cần xử lý 不仅...还..., 取决于 và danh hóa 'cách phản hồi với lỗi sai'.",
      grammar: "不仅...还...; 取决于 + noun phrase.",
      rubric: ["Đúng nghĩa", "Tự nhiên", "Cấu trúc câu", "Từ vựng", "Dấu câu"],
      direction: "vi-zh",
    },
    {
      id: "hsk7-s-topic-001",
      level: 7,
      skill: "speaking",
      section: "Trả lời chủ đề",
      type: "Nói theo chủ đề",
      difficulty: 7,
      source: "original",
      prompt: "请谈一谈你如何安排长期学习计划。要求：观点清楚，至少举一个例子，时间约2分钟。",
      options: ["Ghi âm câu trả lời"],
      answer: "manual",
      translation: "Hãy nói về cách bạn sắp xếp kế hoạch học tập dài hạn. Cần có quan điểm rõ và ít nhất một ví dụ.",
      analysis: "Bài nói tốt cần mở ý nhanh, triển khai ví dụ, kết luận rõ và kiểm soát tốc độ.",
      grammar: "Có thể dùng 首先, 其次, 例如, 总的来说 để tổ chức bài nói.",
      rubric: ["Nội dung", "Tổ chức ý", "Độ lưu loát", "Phát âm", "Từ vựng"],
      taskTime: "2 phút",
    },
    {
      id: "hsk8-l-lecture-001",
      level: 8,
      skill: "listening",
      section: "Bài giảng chuyên sâu",
      type: "Chọn ý chính",
      difficulty: 8,
      source: "original",
      assetStatus: "needs-recorded-audio",
      prompt: "Lời giảng: 当技术改变传播方式时，真正受到挑战的并非阅读本身，而是人们筛选信息和保持深度思考的能力。 Câu hỏi: Ý chính của đoạn là gì?",
      options: ["Công nghệ làm con người ngừng đọc", "Thách thức nằm ở chọn lọc thông tin và tư duy sâu", "Mọi thông tin đều đáng tin", "Đọc truyền thống không còn giá trị"],
      answer: "Thách thức nằm ở chọn lọc thông tin và tư duy sâu",
      transcript: "当技术改变传播方式时，真正受到挑战的并非阅读本身，而是人们筛选信息和保持深度思考的能力。",
      translation: "Khi công nghệ thay đổi cách truyền thông tin, điều bị thách thức không phải bản thân việc đọc, mà là năng lực chọn lọc thông tin và duy trì tư duy sâu.",
      analysis: "Trọng tâm là 并非阅读本身，而是... năng lực xử lý thông tin.",
      grammar: "并非 A，而是 B: không phải A, mà là B.",
    },
    {
      id: "hsk8-r-argument-001",
      level: 8,
      skill: "reading",
      section: "So sánh lập luận",
      type: "Đánh giá lập luận",
      difficulty: 8,
      source: "original",
      prompt: "Đoạn đọc: 有人认为，保护方言会阻碍共同语推广；也有人指出，二者并不矛盾，因为共同语解决跨地区交流，方言保存地方记忆。 Câu hỏi: Cách lập luận của đoạn là gì?",
      options: ["Chỉ đưa một quan điểm", "So sánh hai quan điểm và nêu khả năng dung hòa", "Phủ nhận vai trò giao tiếp", "Chỉ kể chuyện địa phương"],
      answer: "So sánh hai quan điểm và nêu khả năng dung hòa",
      translation: "Có người cho rằng bảo vệ phương ngữ cản trở phổ cập ngôn ngữ chung; có người chỉ ra hai việc không mâu thuẫn.",
      analysis: "Đoạn đặt hai quan điểm đối lập rồi dùng 因为 để giải thích cách dung hòa.",
      grammar: "有人认为...也有人指出...因为...",
    },
    {
      id: "hsk8-w-argument-001",
      level: 8,
      skill: "writing",
      section: "Bình luận quan điểm",
      type: "Bài luận",
      difficulty: 8,
      source: "original",
      prompt: "写一篇400-500字的文章，讨论“人工智能能否代替老师”。要求提出明确观点，分析至少两个理由，并给出结论。",
      options: ["Nộp trong không gian luyện viết"],
      answer: "Bài đạt yêu cầu phải có luận điểm, phân tích hai mặt và kết luận cân bằng.",
      translation: "Viết bài 400-500 chữ bàn về việc AI có thể thay giáo viên hay không.",
      analysis: "Cần đánh giá năng lực hỗ trợ của AI nhưng cũng chỉ ra vai trò phản hồi, động viên và thiết kế lớp học của giáo viên.",
      grammar: "Từ nối đề xuất: 一方面, 另一方面, 然而, 因此.",
      rubric: ["Luận điểm", "Lý do", "Phản biện", "Từ vựng", "Kết luận"],
    },
    {
      id: "hsk8-tr-zhvi-001",
      level: 8,
      skill: "translation",
      section: "Dịch đoạn văn nghị luận",
      type: "Dịch Trung - Việt",
      difficulty: 8,
      source: "original",
      prompt: "Dịch sang tiếng Việt: 教育公平并不意味着所有学生接受完全相同的资源，而是让不同背景的学生都有机会获得适合自己的支持。",
      options: ["Nộp bản dịch"],
      answer: "Công bằng giáo dục không có nghĩa là mọi học sinh nhận nguồn lực hoàn toàn giống nhau, mà là học sinh từ những bối cảnh khác nhau đều có cơ hội nhận được sự hỗ trợ phù hợp với mình.",
      translation: "Education equity does not mean identical resources for all students.",
      analysis: "Cần giữ đối lập 并不意味着...而是... và cụm 适合自己的支持.",
      grammar: "并不意味着 A，而是 B.",
      rubric: ["Đúng nghĩa", "Sắc thái", "Tự nhiên tiếng Việt", "Liên kết câu", "Thuật ngữ"],
      direction: "zh-vi",
    },
    {
      id: "hsk8-s-retell-001",
      level: 8,
      skill: "speaking",
      section: "Tóm tắt và đánh giá",
      type: "Nói tóm tắt",
      difficulty: 8,
      source: "original",
      assetStatus: "needs-recorded-audio",
      prompt: "Nghe một đoạn nói về bảo vệ môi trường đô thị, sau đó tóm tắt hai ý chính và nêu đánh giá cá nhân trong khoảng 3 phút.",
      options: ["Ghi âm câu trả lời"],
      answer: "manual",
      translation: "Task yêu cầu vừa tóm tắt vừa nêu nhận xét cá nhân.",
      analysis: "Không nên kể lại toàn bộ. Cần chọn hai ý chính, đánh giá rõ và dùng từ nối mạch lạc.",
      grammar: "Có thể dùng 主要提到, 我认为, 值得注意的是, 因此.",
      rubric: ["Tóm tắt đúng", "Đánh giá cá nhân", "Mạch lạc", "Lưu loát", "Phát âm"],
      taskTime: "3 phút",
    },
    {
      id: "hsk9-l-debate-001",
      level: 9,
      skill: "listening",
      section: "Đối thoại đa quan điểm",
      type: "Suy luận thái độ",
      difficulty: 9,
      source: "original",
      assetStatus: "needs-recorded-audio",
      prompt: "Tóm tắt tranh luận: một chuyên gia ủng hộ dữ liệu mở nhưng cảnh báo phải có cơ chế bảo vệ quyền riêng tư và trách nhiệm giải trình. Câu hỏi: Thái độ phù hợp nhất là gì?",
      options: ["Ủng hộ tuyệt đối không điều kiện", "Phản đối dữ liệu mở", "Ủng hộ có điều kiện và yêu cầu quản trị", "Không nêu thái độ"],
      answer: "Ủng hộ có điều kiện và yêu cầu quản trị",
      transcript: "开放数据可以促进创新，但前提是建立隐私保护和责任追究机制。",
      translation: "Dữ liệu mở có thể thúc đẩy đổi mới, nhưng điều kiện là xây dựng cơ chế bảo vệ quyền riêng tư và truy cứu trách nhiệm.",
      analysis: "但前提是 cho thấy người nói ủng hộ có điều kiện, không ủng hộ tuyệt đối.",
      grammar: "前提是: điều kiện tiên quyết là.",
    },
    {
      id: "hsk9-r-literature-001",
      level: 9,
      skill: "reading",
      section: "Văn học - văn hóa",
      type: "Đọc hàm ý",
      difficulty: 9,
      source: "original",
      prompt: "Đoạn đọc: 他离开故乡多年，却总在雨夜想起那条窄窄的石板路。路并没有什么特别，只是承载着他无法向别人解释的安宁。 Câu hỏi: Hình ảnh con đường biểu thị điều gì?",
      options: ["Một tuyến giao thông quan trọng", "Ký ức và cảm giác thuộc về", "Sự phát triển đô thị", "Một chuyến đi du lịch"],
      answer: "Ký ức và cảm giác thuộc về",
      translation: "Xa quê nhiều năm, anh vẫn nhớ con đường lát đá trong đêm mưa; nó gánh cảm giác bình yên khó giải thích.",
      analysis: "Hình ảnh 石板路 không quan trọng về chức năng giao thông, mà là biểu tượng ký ức và sự bình yên.",
      grammar: "承载着 + abstract noun: mang/gánh chứa một ý nghĩa trừu tượng.",
    },
    {
      id: "hsk9-w-research-001",
      level: 9,
      skill: "writing",
      section: "Tổng hợp nhiều nguồn",
      type: "Bài luận học thuật",
      difficulty: 9,
      source: "original",
      prompt: "根据两段材料，写一篇500-600字的文章，分析“城市老龄化对公共服务的影响”，并提出两条可行建议。材料必须为原创或授权内容。",
      options: ["Nộp trong không gian luyện viết"],
      answer: "Bài đạt yêu cầu phải tổng hợp nguồn, phân tích tác động và đề xuất giải pháp khả thi.",
      translation: "Dựa trên hai nguồn, viết bài 500-600 chữ phân tích tác động của già hóa đô thị với dịch vụ công.",
      analysis: "Yêu cầu HSK9 cần tổng hợp nhiều nguồn, đánh giá vấn đề và đưa giải pháp có tính khả thi.",
      grammar: "Dùng cấu trúc 因此, 与此同时, 从长远来看, 可行的措施包括.",
      rubric: ["Tổng hợp nguồn", "Phân tích", "Giải pháp", "Tính học thuật", "Kiểm soát ngôn ngữ"],
    },
    {
      id: "hsk9-tr-academic-001",
      level: 9,
      skill: "translation",
      section: "Dịch học thuật",
      type: "Dịch Việt - Trung nâng cao",
      difficulty: 9,
      source: "original",
      prompt: "Dịch sang tiếng Trung: Một chính sách công hiệu quả cần dựa trên dữ liệu đáng tin cậy, nhưng cũng phải xem xét những tác động khó đo lường đối với đời sống cộng đồng.",
      options: ["Nộp bản dịch"],
      answer: "一项有效的公共政策需要建立在可靠的数据基础之上，但也必须考虑那些难以量化、却会影响社区生活的因素。",
      translation: "An effective public policy needs reliable data and must consider hard-to-measure community impacts.",
      analysis: "Khó nhất là xử lý 'tác động khó đo lường' và 'đời sống cộng đồng' tự nhiên bằng tiếng Trung.",
      grammar: "建立在...基础之上; 难以量化; 却...",
      rubric: ["Độ chính xác", "Tính học thuật", "Cấu trúc phức", "Sắc thái", "Tự nhiên"],
      direction: "vi-zh",
    },
    {
      id: "hsk9-s-presentation-001",
      level: 9,
      skill: "speaking",
      section: "Thuyết trình học thuật",
      type: "Trình bày giải pháp",
      difficulty: 9,
      source: "original",
      prompt: "请围绕“如何在技术发展中保护个人隐私”进行4分钟发言。要求说明问题、分析原因、提出至少两项措施。",
      options: ["Ghi âm câu trả lời"],
      answer: "manual",
      translation: "Trình bày 4 phút về cách bảo vệ quyền riêng tư cá nhân trong phát triển công nghệ.",
      analysis: "Cần có cấu trúc vấn đề - nguyên nhân - giải pháp, tránh chỉ liệt kê khẩu hiệu.",
      grammar: "Có thể dùng 首先需要明确, 造成这一问题的原因, 具体措施包括, 总而言之.",
      rubric: ["Cấu trúc", "Chiều sâu phân tích", "Giải pháp", "Lưu loát", "Độ chính xác"],
      taskTime: "4 phút",
    },
  ],
  mockQuestions: [
    { id: "m1", level: 1, skill: "listening", answer: "A", prompt: "Nhận biết lời chào", options: ["A", "B", "C", "D"] },
    { id: "m2", level: 1, skill: "reading", answer: "B", prompt: "Nhận biết danh từ cơ bản", options: ["A", "B", "C", "D"] },
    { id: "m3", level: 2, skill: "listening", answer: "B", prompt: "Biểu đạt thời gian", options: ["A", "B", "C", "D"] },
    { id: "m4", level: 2, skill: "reading", answer: "C", prompt: "Cấu trúc so sánh", options: ["A", "B", "C", "D"] },
    { id: "m5", level: 3, skill: "reading", answer: "D", prompt: "Dấu hiệu hoàn thành 了", options: ["A", "B", "C", "D"] },
    { id: "m6", level: 4, skill: "reading", answer: "A", prompt: "Quan hệ nguyên nhân - kết quả", options: ["A", "B", "C", "D"] },
    { id: "m7", level: 5, skill: "reading", answer: "C", prompt: "Ý chính của đoạn", options: ["A", "B", "C", "D"] },
    { id: "m8", level: 6, skill: "listening", answer: "B", prompt: "Thái độ của người nói", options: ["A", "B", "C", "D"] },
    { id: "m9", level: 6, skill: "reading", answer: "D", prompt: "Câu sai ngữ pháp", options: ["A", "B", "C", "D"] },
    { id: "m10", level: 6, skill: "writing", answer: "manual", prompt: "Bài viết tóm tắt", options: ["manual"] },
    { id: "adv-l1", level: 7, band: "advanced", skill: "listening", answer: "B", prompt: "Nghe bài nghiên cứu giáo dục và chọn trọng tâm", options: ["A", "B", "C", "D"] },
    { id: "adv-r1", level: 7, band: "advanced", skill: "reading", answer: "C", prompt: "Đọc đoạn xã hội học và suy luận quan điểm", options: ["A", "B", "C", "D"] },
    { id: "adv-w1", level: 7, band: "advanced", skill: "writing", answer: "manual", prompt: "Viết tóm tắt 250-300 chữ", options: ["manual"] },
    { id: "adv-tr1", level: 8, band: "advanced", skill: "translation", answer: "manual", prompt: "Dịch đoạn nghị luận giáo dục", options: ["manual"] },
    { id: "adv-s1", level: 8, band: "advanced", skill: "speaking", answer: "manual", prompt: "Nói tóm tắt và đánh giá trong 3 phút", options: ["manual"] },
    { id: "adv-l2", level: 9, band: "advanced", skill: "listening", answer: "C", prompt: "Nghe tranh luận dữ liệu mở và suy luận thái độ", options: ["A", "B", "C", "D"] },
    { id: "adv-r2", level: 9, band: "advanced", skill: "reading", answer: "B", prompt: "Đọc văn bản văn hóa và xác định hàm ý", options: ["A", "B", "C", "D"] },
    { id: "adv-w2", level: 9, band: "advanced", skill: "writing", answer: "manual", prompt: "Viết bài tổng hợp nhiều nguồn", options: ["manual"] },
  ],
  mockSets: [
    { id: "real-1", level: 1, group: "Đề thi thử chuẩn", name: "Bộ đề thi thử số 1", status: "open", questions: 40, duration: 40 },
    { id: "real-2", level: 2, group: "Đề thi thử chuẩn", name: "Bộ đề thi thử số 2", status: "open", questions: 60, duration: 55 },
    { id: "real-3", level: 3, group: "Đề thi thử chuẩn", name: "Bộ đề thi thử số 3", status: "open", questions: 80, duration: 90 },
    { id: "real-4", level: 4, group: "Đề thi thử chuẩn", name: "Bộ đề thi thử số 4", status: "vip", questions: 100, duration: 105 },
    { id: "real-5", level: 5, group: "Đề thi thử chuẩn", name: "Bộ đề thi thử số 5", status: "vip", questions: 100, duration: 125 },
    { id: "real-6", level: 6, group: "Đề thi thử chuẩn", name: "Bộ đề thi thử số 6", status: "vip", questions: 101, duration: 140 },
    { id: "pack-1", level: 6, group: "Kho đề luyện", name: "Bộ luyện đề số 1", status: "vip", questions: 101, duration: 140 },
    { id: "pack-2", level: 6, group: "Kho đề luyện", name: "Bộ luyện đề số 2", status: "vip", questions: 101, duration: 140 },
    { id: "pack-3", level: 5, group: "Kho đề luyện", name: "Bộ luyện đề số 3", status: "vip", questions: 100, duration: 125 },
    { id: "adaptive-1", level: 4, group: "Đề mini thích ứng", name: "Đề nhanh theo điểm yếu", status: "open", questions: 20, duration: 25 },
    { id: "advanced-789-open", level: 7, band: "advanced", group: "HSK 7-9 nâng cao", name: "Đề định vị Advanced HSK 7-9", status: "open", questions: 98, duration: 210 },
    { id: "advanced-789-full-1", level: 8, band: "advanced", group: "HSK 7-9 nâng cao", name: "Đề mô phỏng 210 phút số 1", status: "vip", questions: 98, duration: 210 },
    { id: "advanced-789-full-2", level: 9, band: "advanced", group: "Kho đề nâng cao", name: "Đề mô phỏng phân loại 7/8/9 số 2", status: "vip", questions: 98, duration: 210 },
    { id: "advanced-skill-translation", level: 8, band: "advanced", group: "Đề mini kỹ năng yếu", name: "Mini mock Dịch nâng cao", status: "open", questions: 12, duration: 35 },
    { id: "advanced-skill-speaking", level: 8, band: "advanced", group: "Đề mini kỹ năng yếu", name: "Mini mock Nói nâng cao", status: "vip", questions: 6, duration: 30 },
  ],
  vocab: [
    { hanzi: "我", pinyin: "wǒ", meaning: "tôi", level: 1, due: "today", mastery: 82, example: "我是学生。" },
    { hanzi: "学习", pinyin: "xuéxí", meaning: "học tập", level: 1, due: "today", mastery: 72, example: "我学习汉语。" },
    { hanzi: "学校", pinyin: "xuéxiào", meaning: "trường học", level: 1, due: "tomorrow", mastery: 65, example: "我去学校。" },
    { hanzi: "考试", pinyin: "kǎoshì", meaning: "kỳ thi", level: 2, due: "today", mastery: 68, example: "明天有考试。" },
    { hanzi: "比较", pinyin: "bǐjiào", meaning: "khá, tương đối; so sánh", level: 2, due: "tomorrow", mastery: 51, example: "今天比较冷。" },
    { hanzi: "以前", pinyin: "yǐqián", meaning: "trước đây", level: 3, due: "today", mastery: 47, example: "我以前住在北京。" },
    { hanzi: "提高", pinyin: "tígāo", meaning: "nâng cao", level: 3, due: "tomorrow", mastery: 55, example: "我要提高听力。" },
    { hanzi: "取消", pinyin: "qǔxiāo", meaning: "hủy bỏ", level: 4, due: "today", mastery: 41, example: "比赛取消了。" },
    { hanzi: "经验", pinyin: "jīngyàn", meaning: "kinh nghiệm", level: 4, due: "today", mastery: 39, example: "他有很多经验。" },
    { hanzi: "效率", pinyin: "xiàolǜ", meaning: "hiệu suất", level: 5, due: "3 days", mastery: 29, example: "这样做效率很高。" },
    { hanzi: "机会", pinyin: "jīhuì", meaning: "cơ hội", level: 5, due: "today", mastery: 33, example: "这是一个好机会。" },
    { hanzi: "概括", pinyin: "gàikuò", meaning: "khái quát", level: 6, due: "today", mastery: 18, example: "请概括文章的主要内容。" },
    { hanzi: "自律", pinyin: "zìlǜ", meaning: "tự giác, kỷ luật bản thân", level: 6, due: "today", mastery: 24, example: "学习需要自律。" },
    { hanzi: "归属感", pinyin: "guīshǔgǎn", meaning: "cảm giác thuộc về", level: 7, due: "today", mastery: 12, example: "社区活动能增强居民的归属感。" },
    { hanzi: "筛选", pinyin: "shāixuǎn", meaning: "sàng lọc, chọn lọc", level: 7, due: "tomorrow", mastery: 16, example: "我们需要学会筛选可靠的信息。" },
    { hanzi: "量化", pinyin: "liànghuà", meaning: "lượng hóa", level: 8, due: "today", mastery: 9, example: "有些社会影响很难量化。" },
    { hanzi: "责任追究", pinyin: "zérèn zhuījiū", meaning: "truy cứu trách nhiệm", level: 8, due: "3 days", mastery: 11, example: "制度应包括责任追究机制。" },
    { hanzi: "长远来看", pinyin: "chángyuǎn lái kàn", meaning: "nhìn về dài hạn", level: 9, due: "today", mastery: 7, example: "从长远来看，教育投资非常重要。" },
    { hanzi: "公共政策", pinyin: "gōnggòng zhèngcè", meaning: "chính sách công", level: 9, due: "tomorrow", mastery: 8, example: "公共政策需要兼顾效率和公平。" },
  ],
  appDownload: {
    tagline: "Ứng dụng đồng hành để luyện HSK 1-9, thi thử, ôn từ vựng, nhận xét bài viết, luyện dịch/nói và kết nối giáo viên.",
    features: [
      ["Chẩn đoán trình độ", "Ước tính cấp HSK hiện tại và kỹ năng yếu từ một bài làm ngắn."],
      ["Lộ trình cá nhân", "Tạo việc học hằng ngày theo mục tiêu, ngày thi, lịch sử câu sai và lịch ôn."],
      ["Luyện tập tối ưu", "Ưu tiên dạng câu ảnh hưởng nhiều nhất tới điểm mục tiêu."],
      ["Ôn ngoại tuyến", "Xếp hàng từ vựng và giải thích đã lưu để ôn trên điện thoại."],
      ["HSK 7-9 nâng cao", "Bộ luyện Nghe, Đọc, Viết, Dịch, Nói theo bài Advanced 210 phút."],
      ["Hỗ trợ giáo viên", "Chuyển yêu cầu sửa bài, dịch, nói và gia sư vào quy trình giáo viên."],
    ],
    stores: [
      ["Tải iOS", "TODO: URL App Store gốc"],
      ["Tải Android", "TODO: URL Google Play/APK gốc"],
    ],
  },
  examInfo: [
    { level: 1, words: 150, duration: "Khoảng 40 phút", content: "Nghe 20 câu, Đọc 20 câu", outcome: "Hiểu và sử dụng các từ/câu tiếng Trung rất đơn giản." },
    { level: 2, words: 300, duration: "Khoảng 55 phút", content: "Nghe 35 câu, Đọc 25 câu", outcome: "Giao tiếp đơn giản trong các tình huống đời sống trực tiếp." },
    { level: 3, words: 600, duration: "Khoảng 90 phút", content: "Nghe, Đọc, Viết", outcome: "Xử lý giao tiếp cơ bản trong đời sống, học tập và công việc." },
    { level: 4, words: 1200, duration: "Khoảng 105 phút", content: "Nghe, Đọc, Viết", outcome: "Trao đổi về nhiều chủ đề và giao tiếp với người bản ngữ trôi chảy hơn." },
    { level: 5, words: 2500, duration: "Khoảng 125 phút", content: "Nghe, Đọc, Viết", outcome: "Đọc tài liệu dài hơn và diễn đạt ý hoàn chỉnh hơn." },
    { level: 6, words: 5000, duration: "Khoảng 140 phút", content: "Nghe, Đọc, Viết tóm tắt", outcome: "Hiểu thông tin tiếng Trung phức tạp và trình bày ý hiệu quả." },
    { level: 7, words: 11092, duration: "Khoảng 210 phút", content: "Bài Advanced chung: Nghe, Đọc, Viết, Dịch, Nói", outcome: "Sử dụng tiếng Trung nâng cao trong học thuật, nghề nghiệp và giao tiếp phức tạp." },
    { level: 8, words: 11092, duration: "Khoảng 210 phút", content: "Bài Advanced chung: Nghe, Đọc, Viết, Dịch, Nói", outcome: "Phân tích, tổng hợp và trình bày quan điểm phức tạp với độ chính xác cao." },
    { level: 9, words: 11092, duration: "Khoảng 210 phút", content: "Bài Advanced chung: Nghe, Đọc, Viết, Dịch, Nói", outcome: "Dùng tiếng Trung ở mức thành thạo cao cho nghiên cứu, diễn thuyết, dịch thuật và tranh luận." },
  ],
  examSchedule: {
    "2024": [
      { date: "2024-03-16", subject: "HSK", paperDeadline: "Verify official source", onlineDeadline: "Verify official source", result: "Verify official source" },
      { date: "2024-06-22", subject: "HSK", paperDeadline: "Verify official source", onlineDeadline: "Verify official source", result: "Verify official source" },
    ],
    "2025": [
      { date: "2025-03-22", subject: "HSK", paperDeadline: "Verify official source", onlineDeadline: "Verify official source", result: "Verify official source" },
      { date: "2025-11-15", subject: "HSK", paperDeadline: "Verify official source", onlineDeadline: "Verify official source", result: "Verify official source" },
    ],
    "2026": [
      { date: "2026-01-24", subject: "HSK", paperDeadline: "2025-12-28", onlineDeadline: "2026-01-14", result: "2026-03-03 / 2026-02-09" },
      { date: "2026-03-22", subject: "HSK", paperDeadline: "2026-02-23", onlineDeadline: "2026-03-12", result: "2026-04-22 / 2026-04-07" },
      { date: "2026-04-11", subject: "HSK", paperDeadline: "2026-03-15", onlineDeadline: "2026-04-01", result: "2026-05-15 / 2026-04-27" },
      { date: "2026-05-16", subject: "HSK", paperDeadline: "2026-04-19", onlineDeadline: "2026-05-06", result: "2026-06-16 / 2026-06-01" },
      { date: "2026-06-28", subject: "HSK", paperDeadline: "2026-06-01", onlineDeadline: "2026-06-18", result: "2026-07-28 / 2026-07-13" },
      { date: "2026-07-18", subject: "HSK", paperDeadline: "2026-06-21", onlineDeadline: "2026-07-08", result: "2026-08-19 / 2026-08-03" },
    ],
  },
  regulationTopics: [
    { key: "registration", title: "Đăng ký thi và thanh toán lệ phí", body: "Hướng dẫn người học tạo tài khoản ở trang thi chính thức, chọn cấp độ, hình thức, điểm thi, ngày thi, thanh toán và xác nhận." },
    { key: "photo", title: "Yêu cầu ảnh thí sinh", body: "Checklist về định dạng ảnh, khuôn mặt, nền, thời hạn ảnh và trạng thái duyệt ảnh." },
    { key: "ticket", title: "Phiếu dự thi", body: "Theo dõi thời điểm có phiếu dự thi, trạng thái tải/in, địa chỉ điểm thi và nhắc lịch." },
    { key: "change", title: "Đổi ngày thi", body: "Giải thích thời hạn được đổi ngày, phí đổi ngày và quy trình hỗ trợ trước hạn đăng ký." },
    { key: "rules", title: "Quy định phòng thi", body: "Quy định ngày thi: giờ có mặt, giấy tờ, vật dụng cấm, cách xử lý phiếu trả lời và cảnh báo vi phạm." },
    { key: "scores", title: "Điểm thi", body: "Theo dõi ngày công bố điểm, giải thích chứng chỉ, mục tiêu đậu và kế hoạch cải thiện sau thi." },
    { key: "services", title: "Dịch vụ bổ sung", body: "Hỗ trợ gửi bảng điểm, gia sư, kế hoạch thi lại và báo cáo cho tổ chức." },
  ],
  tutoringModules: [
    ["Tổng hợp trọng điểm HSK", "Sơ đồ kiến thức do giáo viên biên soạn cho từng cấp và dạng câu."],
    ["Giải thích kỹ năng học HSK", "Bài chiến thuật cho nghe, đọc, viết, quản lý thời gian và loại trừ đáp án."],
    ["Phân tích xu hướng đề", "Phân tích xu hướng từ bộ dữ liệu được cấp phép hoặc tự biên soạn."],
    ["Huấn luyện HSK 7-9", "Lộ trình nâng cao cho bài Advanced: dịch, nói, viết học thuật, đọc dài và nghe tốc độ tự nhiên."],
    ["Gia sư 1-1", "Đặt lịch, phân giáo viên, ghi chú buổi học, bài tập và gia hạn."],
    ["Sửa bài viết", "AI nhận xét bước đầu, giáo viên chấm theo rubric, vòng sửa lại và trừ tín chỉ."],
  ],
  accountModules: [
    ["Thông tin cá nhân", "Biệt danh, email/số điện thoại, quốc tịch, nơi ở hiện tại, mục tiêu HSK."],
    ["Tin nhắn", "Thông báo hệ thống, phản hồi giáo viên, thông báo thanh toán và hỗ trợ."],
    ["Thẻ thành viên", "Ngày hết hạn, trạng thái gói, gia hạn và quyền lợi."],
    ["Đổi mã ưu đãi", "Nhập mã, coupon chiến dịch, tín chỉ giáo viên sửa bài."],
    ["Phản hồi", "Loại vấn đề, ảnh/chứng cứ đính kèm, trạng thái hỗ trợ."],
    ["Mật khẩu", "Đặt lại mật khẩu, phiên đăng nhập thiết bị, xác minh hai bước."],
    ["Xóa tài khoản", "Xuất dữ liệu, cảnh báo lưu giữ và quy trình yêu cầu xóa."],
  ],
  corporateModules: [
    ["Tổ chức", "Hồ sơ công ty/trường, số chỗ học, liên hệ thanh toán, trạng thái hợp đồng."],
    ["Lớp học", "Danh sách học viên, mục tiêu HSK, bài giao, hạn nộp và giáo viên phụ trách."],
    ["Dashboard giáo viên", "Tiến độ học viên, heatmap câu sai, hàng đợi chấm bài viết."],
    ["Bài giao", "Bộ luyện tập, đề thi thử, danh sách từ vựng, bài viết và hạn nộp."],
    ["Báo cáo", "Phân bố trình độ, điểm sẵn sàng, điểm danh, hoàn thành và xuất file."],
  ],
  testimonials: [
    { name: "Học viên A", level: "HSK4", score: "270+", text: "Câu chuyện mẫu. Khi có học viên thật, cần lưu sự đồng ý sử dụng nội dung." },
    { name: "Học viên B", level: "HSK5", score: "260+", text: "Câu chuyện mẫu. Admin cần lưu xác nhận, quốc gia và minh chứng điểm." },
    { name: "Học viên C", level: "HSK6", score: "250+", text: "Câu chuyện mẫu. Không sao chép testimonial từ bên thứ ba." },
  ],
  plans: [
    {
      name: "Free",
      price: "$0",
      features: ["Chẩn đoán mẫu", "Giới hạn luyện HSK 1-2", "Từ vựng khởi động", "Tiến độ cơ bản"],
      entitlements: ["basic-practice", "starter-vocab"],
    },
    {
      name: "VIP",
      price: "$9/mo",
      features: ["Luyện HSK 1-6", "Luyện thông minh", "Thi thử", "Ôn câu sai", "Ghi chú và bộ sưu tập"],
      entitlements: ["full-practice", "smart-quiz", "mock-tests", "repository"],
    },
    {
      name: "MAX",
      price: "$19/mo",
      features: ["HSK 7-9 Advanced", "AI sửa bài viết/dịch/nói", "Phòng luyện nói", "Lộ trình thích ứng", "Báo cáo sâu"],
      entitlements: ["advanced-hsk", "ai-writing", "translation", "speaking", "adaptive-plan", "advanced-reports"],
    },
    {
      name: "Organization",
      price: "Custom",
      features: ["Dashboard giáo viên", "Lớp học", "Bài giao", "Quản lý chỗ học", "Báo cáo doanh nghiệp"],
      entitlements: ["org-admin", "classes", "teacher-reports", "seat-management"],
    },
  ],
  protectedCloneTodo: [
    "Tên ứng dụng, logo, icon, màu thương hiệu và thông tin pháp lý gốc.",
    "Đề thi thử HSK được cấp phép hoặc tự biên soạn.",
    "Phân bổ chi tiết câu hỏi HSK 7-9, rubric chính thức và bộ đề Advanced phải kiểm chứng/cấp phép trước khi thương mại hóa.",
    "Audio do người bản ngữ thu cho từng câu nghe.",
    "Audio bài nói mẫu, corpus phát âm và dữ liệu chấm nói/dịch cho HSK 7-9.",
    "Hình ảnh gốc cho bài nối ảnh và đề viết theo tranh.",
    "Tài khoản thanh toán, bản địa hóa giá và cấu hình thuế.",
    "Quy trình giáo viên sửa bài và điều khoản dịch vụ.",
    "Chính sách riêng tư, điều khoản, hoàn tiền và nội dung xóa dữ liệu.",
  ],
};
